### ISSUE TITLE
Right clicking

### ISSUE THREAD

**Issue by Anxiousaurus** [chudders1231/UpdatedLegacyMods#1]
Autosort lockers used to allow right clicking to navigate the options on the locker menu in legacy. This was superior to left clicking because it didn't interact with any objects behind the locker, now in tight spaces, it prevents users from making adjustments. Please bring back right clicking.

**Comment by crystalinerose** [comment]
I highly appreciate combining AutosortLockers with DockedVehicleStorageAccess in this 2.0 updated version, but please add an autosort on/off toggle for the vehicle unloader, so users can manage the vehicle inventory without the items immediately getting unloaded into receptacles in any given base. Personally, sometimes I dock at a base for a food/water resupply break, and the items inside my vehicle's storage are important items I've placed in there for the next trip outside the base. I wouldn't want that to be unloaded every time I dock and have to hunt them down again to re-place in the docked vehicle's storage.

**Comment by chudders1231** [comment]
Ahh yes, this was fixed a while ago as it felt jarring to be able to left or right click the menus but i understand the use case here. I shall add this to my trello, and it will be fixed in the next update
