### ISSUE TITLE
AutoSort Vehicle Unloader pulling torpedoes from torpedo bay on docked Seamoth

### ISSUE THREAD

**Issue by TheDarkFae** [chudders1231/UpdatedLegacyMods#4]
Posting here as requested on the Discord; the vehicle unloader pulls torpedoes from the loaded torpedo bay on a docked Seamoth. I will add that this is a modded Seamoth for additional slots, though the torpedo upgrade is the vanilla modification, and added to one of the first four slots. If you want me to check with a vanilla Seamoth, or if you have any questions about the other mods I'm running for the Seamoth, feel free to reach out to me on Discord @ darkfaegaming

**Comment by chudders1231** [comment]
Fixed.
Will be included in the next update.
